### ISSUE TITLE
bloody altar shouldnt generate in basalt deltas

### ISSUE THREAD

**Issue by nameedo** [EEEAB/EEEABsMobs#10]
![2024-06-02_09 13 03](https://github.com/EEEAB/EEEABsMobs/assets/154930467/5ee35947-68df-4ddd-8756-05cd07676ec8)

**Comment by EEEAB** [comment]
Thank you for your feedback. The generation area tag for the structure (bloody_altar) is defined too broadly, which from a developer's perspective is aimed at accommodating mods that introduce additional Nether biomes for compatibility. Nevertheless, I acknowledge that from a player's point of view, finding this structure within basalt deltas can be a significant annoyance. This issue is set to be refined in future updates. 

Even so, I must be honest and say that due to the potential for this structure to generate along the boundaries of other Nether biomes intersecting with basalt deltas, I cannot promise that such instances will be entirely eradicated.
